# S50 Contestant Pool - Survivor 50: In the Hands of the Fans
# 24 returning players across 3 starting tribes (8 per tribe)
# Photos from Survivor Wiki (Fandom)

contestants:
  - id: c01
    name: "Rick Devens"
    starting_tribe: "Tribe A"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/4/47/S50_Rick_Devens.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.3
    survival_bias: 0.5
  - id: c02
    name: "Cirie Fields"
    starting_tribe: "Tribe A"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/5/5c/S50_Cirie_Fields.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.4
    survival_bias: 0.7
  - id: c03
    name: "Emily Flippen"
    starting_tribe: "Tribe A"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/3/33/S50_Emily_Flippen.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.3
    survival_bias: 0.5
  - id: c04
    name: "Christian Hubicki"
    starting_tribe: "Tribe A"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/8/89/S50_Christian_Hubicki.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.3
    survival_bias: 0.5
  - id: c05
    name: "Joe Hunter"
    starting_tribe: "Tribe A"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/3/3e/S50_Joe_Hunter.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.3
    survival_bias: 0.5
  - id: c06
    name: "Jenna Lewis-Dougherty"
    starting_tribe: "Tribe A"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/e/e4/S50_Jenna_Lewis-Dougherty.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.3
    survival_bias: 0.5
  - id: c07
    name: "Savannah Louie"
    starting_tribe: "Tribe A"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/9/91/S50_Savannah_Louie.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.3
    survival_bias: 0.6
  - id: c08
    name: "Ozzy Lusth"
    starting_tribe: "Tribe A"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/f/f6/S50_Ozzy_Lusth.jpg/revision/latest"
    challenge_ability: 0.8
    idol_likelihood: 0.2
    survival_bias: 0.7
  - id: c09
    name: "Charlie Davis"
    starting_tribe: "Tribe B"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/8/84/S50_Charlie_Davis.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.3
    survival_bias: 0.5
  - id: c10
    name: "Tiffany Ervin"
    starting_tribe: "Tribe B"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/e/e0/S50_Tiffany_Nicole_Ervin.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.3
    survival_bias: 0.5
  - id: c11
    name: "Chrissy Hofbeck"
    starting_tribe: "Tribe B"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/b/b3/S50_Chrissy_Hofbeck.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.3
    survival_bias: 0.6
  - id: c12
    name: "Kamilla Karthigesu"
    starting_tribe: "Tribe B"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/e/e9/S50_Kamilla_Karthigesu.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.3
    survival_bias: 0.5
  - id: c13
    name: "Dee Valladares"
    starting_tribe: "Tribe B"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/2/2b/S50_Dee_Valladares.jpg/revision/latest"
    challenge_ability: 0.6
    idol_likelihood: 0.3
    survival_bias: 0.6
  - id: c14
    name: "Coach Wade"
    starting_tribe: "Tribe B"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/a/a8/S50_Coach_Wade.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.4
    survival_bias: 0.5
  - id: c15
    name: "Mike White"
    starting_tribe: "Tribe B"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/a/ad/S50_Mike_White.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.3
    survival_bias: 0.6
  - id: c16
    name: "Jonathan Young"
    starting_tribe: "Tribe B"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/2/2c/S50_Jonathan_Young.jpg/revision/latest"
    challenge_ability: 0.7
    idol_likelihood: 0.2
    survival_bias: 0.6
  - id: c17
    name: "Aubry Bracco"
    starting_tribe: "Tribe C"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/7/73/S50_Aubry_Bracco.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.4
    survival_bias: 0.5
  - id: c18
    name: "Q Burdette"
    starting_tribe: "Tribe C"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/f/f9/S50_Q_Burdette.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.3
    survival_bias: 0.5
  - id: c19
    name: "Colby Donaldson"
    starting_tribe: "Tribe C"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/8/82/S50_Colby_Donaldson.jpg/revision/latest"
    challenge_ability: 0.6
    idol_likelihood: 0.2
    survival_bias: 0.6
  - id: c20
    name: "Kyle Fraser"
    starting_tribe: "Tribe C"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/d/db/S50_Kyle_Fraser.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.3
    survival_bias: 0.5
  - id: c21
    name: "Angelina Keeley"
    starting_tribe: "Tribe C"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/0/00/S50_Angelina_Keeley.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.4
    survival_bias: 0.5
  - id: c22
    name: "Stephenie LaGrossa Kendrick"
    starting_tribe: "Tribe C"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/f/f5/S50_Stephenie_LaGrossa_Kendrick.jpg/revision/latest"
    challenge_ability: 0.6
    idol_likelihood: 0.3
    survival_bias: 0.6
  - id: c23
    name: "Genevieve Mushaluk"
    starting_tribe: "Tribe C"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/8/82/S50_Genevieve_Mushaluk.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.3
    survival_bias: 0.5
  - id: c24
    name: "Rizo Velovic"
    starting_tribe: "Tribe C"
    photo_url: "https://static.wikia.nocookie.net/survivor/images/8/8b/S50_Rizo_Velovic.jpg/revision/latest"
    challenge_ability: 0.5
    idol_likelihood: 0.3
    survival_bias: 0.5
